#!/bin/bash
# Deploy / update the projector web remote. Idempotent: safe to re-run after edits.
# Usage: ./deploy.sh [--rotate-token]
set -euo pipefail

. "$(cd "$(dirname "$0")" && pwd)/lib.sh"   # TV, IP, PORT, HTTPS, REMOTE, HERE

if [ ! -f "$HERE/device/cert.pem" ]; then
  echo "!! no cert — run ./gen-cert.sh first"; exit 1
fi

# Always rebuild the proxy. Skipping this ships a stale binary while every source
# file looks correct — the most confusing possible failure.
echo ">> build tls proxy (all ABIs)"
"$HERE/build.sh"

echo ">> connect + root + remount"
adb_connect || { echo "!! adb root refused (production build?) — boot persistence needs it"; exit 1; }
adb -s "$TV" remount >/dev/null

# Which binary this box needs. Selected from the device's own ABI, not assumed,
# so the same repo deploys to an arm64 or x86_64 box unchanged.
BIN="$(select_binary)" || exit 1
echo "   device ABI -> $BIN"

# ---- auth token ------------------------------------------------------------
# Lives only on the device (0600). Reused across deploys on purpose: rotating it
# invalidates every phone's saved home-screen shortcut and cookie.
echo ">> auth token"
tok=$(adb -s "$TV" shell "cat $REMOTE/token 2>/dev/null" | tr -d '\r\n' || true)
if [ "${1:-}" = "--rotate-token" ] || [ -z "$tok" ]; then
  [ -n "$tok" ] && echo "   !! rotating — every phone must reopen the new URL"
  tok=$(openssl rand -hex 16)
  adb -s "$TV" shell "mkdir -p $REMOTE; printf '%s' '$tok' > $REMOTE/token; chmod 600 $REMOTE/token"
  echo "   new token generated"
else
  echo "   reusing existing token"
fi

echo ">> push web app to $REMOTE"
adb -s "$TV" shell "mkdir -p $REMOTE/bin"

# Device-side copy of the config. boot.sh sources this and passes it to the
# proxy as flags, so the on-device binary carries no baked-in address and the
# same binary works on any box.
cat > "$HERE/device/config" <<EOF
# Generated by deploy.sh -- edit config.local.env on the Mac, not this file.
HTTPS_PORT=$HTTPS
REMOTE_DIR=$REMOTE
MDNS_HOST=$MDNS_HOST
ADV_IP=$IP
EOF
adb -s "$TV" push "$HERE/device/config" "$REMOTE/config" >/dev/null
adb -s "$TV" push "$HERE/device/boot.sh"    "$REMOTE/boot.sh"
adb -s "$TV" push "$HERE/device/bin/$BIN" "$REMOTE/bin/tlsproxy"
adb -s "$TV" push "$HERE/device/cert.pem"   "$REMOTE/cert.pem"   # fullchain: leaf + CA
adb -s "$TV" push "$HERE/device/key.pem"    "$REMOTE/key.pem"
adb -s "$TV" push "$HERE/device/ca.crt"     "$REMOTE/ca.crt"     # CA for iPhone to trust
# Sweep the old layout off any box upgraded from it. This is not tidiness:
#
#   start.sh  -- the original launcher, which starts busybox httpd with `-p 8790`
#                and NO 127.0.0.1 prefix, i.e. bound to 0.0.0.0. Anything that
#                ran it would re-expose key.pem and the token to the whole LAN,
#                as root. It is the exact bug this project already fixed once,
#                sitting on disk waiting to be executed.
#   index.html -- the UI is embedded now; a stale copy on disk would be the
#                 wrong UI the moment anything served it again.
#   cgi-bin    -- root-executing scripts with no reason to exist.
adb -s "$TV" shell "rm -rf $REMOTE/cert.crt $REMOTE/index.html $REMOTE/cgi-bin \
    $REMOTE/start.sh $REMOTE/httpd.log; \
  chmod 755 $REMOTE/boot.sh $REMOTE/bin/tlsproxy; \
  chmod 644 $REMOTE/cert.pem $REMOTE/ca.crt; chmod 600 $REMOTE/key.pem $REMOTE/token"

echo ">> install boot service /vendor/etc/init/tvremote.rc"
adb -s "$TV" push "$HERE/device/tvremote.rc" /vendor/etc/init/tvremote.rc
adb -s "$TV" shell "chmod 644 /vendor/etc/init/tvremote.rc; chown root:root /vendor/etc/init/tvremote.rc; \
  chcon u:object_r:vendor_configs_file:s0 /vendor/etc/init/tvremote.rc"

# A box upgraded from the busybox layout has an httpd that init never owned, so
# ctl.restart leaves it running and it keeps serving the install dir on the LAN.
echo ">> stop any stale busybox backend (pre-embed layout)"
adb -s "$TV" shell "pkill -f 'busybox httpd' 2>/dev/null; true" >/dev/null 2>&1 || true

echo ">> (re)start service now, no reboot needed"
svc=$(adb -s "$TV" shell 'getprop init.svc.tvremote' | tr -d '\r')
if [ -n "$svc" ]; then
  # init knows the service (installed on a prior boot) -> just re-exec it
  adb -s "$TV" shell "setprop ctl.restart tvremote" >/dev/null 2>&1 || true
else
  # first deploy before any reboot: launch once, fully detached so adb returns
  adb -s "$TV" shell "( setsid /system/bin/sh $REMOTE/boot.sh >$REMOTE/boot.log 2>&1 </dev/null & ); exit" >/dev/null 2>&1 || true
fi

echo ">> verify"
sleep 3
# curl prints 000 to stdout on a connection failure but also exits nonzero, which
# set -e would treat as fatal; swallow the status and keep the code.
code(){ local c; c=$(curl -sk -m6 -o /dev/null -w '%{http_code}' "$@" 2>/dev/null) || c=000; echo "${c:-000}"; }

noauth=$(code "https://$IP:$HTTPS/")                 # must be 401
auth=$(code -H "Cookie: tvr=$tok" "https://$IP:$HTTPS/")
ca=$(code "http://$IP:$HTTPS/ca.crt")                # plaintext bootstrap, must be 200
# Proves input injection really runs, not just that the server answers. Paired
# up/down so the check leaves the volume where it found it.
key=$(code -H "Cookie: tvr=$tok" "https://$IP:$HTTPS/cgi-bin/k?volup")
code -H "Cookie: tvr=$tok" "https://$IP:$HTTPS/cgi-bin/k?voldown" >/dev/null
# Nothing is served off the filesystem now, but assert it anyway: this pair is
# what caught the TLS private key being downloadable over the LAN, and a future
# static-file handler would silently reintroduce it.
leakkey=$(code -H "Cookie: tvr=$tok" "https://$IP:$HTTPS/key.pem")
leaktok=$(code -H "Cookie: tvr=$tok" "https://$IP:$HTTPS/token")
# The UI must actually come back. A 200 alone would also be satisfied by an
# empty body if the embed ever broke.
ui=$(curl -sk -m6 -H "Cookie: tvr=$tok" "https://$IP:$HTTPS/" 2>/dev/null | grep -c '<html' || true)
# Upgrade hazard, not a permanent one: a box deployed under the old layout has a
# busybox httpd that init does not supervise, so it survives ctl.restart and
# keeps serving the whole install dir as root on the LAN. Assert it is gone.
# `grep -c` exits 1 on zero matches, so the || has to live INSIDE the device
# shell -- putting it outside appends a second value to the one grep printed.
stray=$(adb -s "$TV" shell "toybox netstat -ltn 2>/dev/null | grep -c ':$LEGACY_BACKEND_PORT ' || true" | tr -d '\r' | head -1)

echo "   no token           https://$IP:$HTTPS/          -> $noauth   (want 401)"
echo "   with token         https://$IP:$HTTPS/          -> $auth   (want 200)"
echo "   UI body served     <html> in response           -> $ui   (want 1)"
echo "   CA over plaintext  http://$IP:$HTTPS/ca.crt     -> $ca   (want 200)"
echo "   a key press        …/cgi-bin/k?volup            -> $key   (want 200)"
echo "   TLS key w/ token   …/key.pem                    -> $leakkey   (want 404)"
echo "   token w/ token     …/token                      -> $leaktok   (want 404)"
echo "   stale busybox      listeners on :$LEGACY_BACKEND_PORT           -> $stray   (want 0)"

fail=0
[ "$noauth" = 401 ] || { echo "!! unauthenticated request was not rejected"; fail=1; }
[ "$auth"   = 200 ] || { echo "!! tokenized request failed"; fail=1; }
[ "$ui"     = 1   ] || { echo "!! the page came back empty — the embedded UI is broken"; fail=1; }
[ "$ca"     = 200 ] || { echo "!! ca.crt not served in the clear — a new phone can't bootstrap trust"; fail=1; }
[ "$key"     = 200 ] || { echo "!! key injection endpoint failed"; fail=1; }
[ "$leakkey" = 404 ] || { echo "!! the TLS PRIVATE KEY is downloadable"; fail=1; }
[ "$leaktok" = 404 ] || { echo "!! the auth token itself is downloadable"; fail=1; }
[ "$stray"   = 0   ] || { echo "!! a stale busybox httpd is still serving the install dir on :$LEGACY_BACKEND_PORT"; fail=1; }
if [ "$fail" != 0 ]; then echo "FAILED (see: ./logs.sh)"; exit 1; fi

echo "OK."
echo
echo "REMOTE URL (contains the token — treat it like a password):"
echo "  https://$IP:$HTTPS/?t=$tok"
echo
echo "iPhone (one-time): DELETE any old 'Projector Remote' profile first, then:"
echo "  1) Safari -> http://$IP:$HTTPS/ca.crt  -> install the 'Projector Remote Local CA' profile"
echo "  2) Settings > General > About > Certificate Trust Settings -> turn it ON"
echo "  3) force-quit Safari, then open the tokenized URL above -> Add to Home Screen"
echo "     (add it WITH ?t=… so the shortcut re-authorizes itself if the cookie is ever evicted)"
