#!/bin/bash
# Deploy / update the projector web remote. Idempotent: safe to re-run after edits.
# Usage: ./deploy.sh [--rotate-token]
set -euo pipefail

. "$(cd "$(dirname "$0")" && pwd)/lib.sh"   # TV, IP, PORT, HTTPS, REMOTE, HERE

if [ ! -f "$HERE/device/cert.pem" ]; then
  echo "!! no cert — run ./gen-cert.sh first"; exit 1
fi

# Always rebuild the proxy. Skipping this ships a stale binary while every source
# file looks correct — the most confusing possible failure.
echo ">> build tls proxy (all ABIs)"
"$HERE/build.sh"

echo ">> connect + probe"
if adb_connect; then ROOT=1; else ROOT=0; fi

# Which binary this box needs. Selected from the device's own ABI, not assumed,
# so the same repo deploys to an arm64 or x86_64 box unchanged.
BIN="$(select_binary)" || exit 1

# Probe rather than assume. This projector is a userdebug build with SELinux
# Permissive and a writable /vendor; a retail Android TV box is none of those,
# and the difference decides whether boot persistence is possible at all.
probe(){ adb -s "$TV" shell "$1" 2>/dev/null | tr -d '\r'; }
SELINUX="$(probe getenforce)"
BUILDTYPE="$(probe 'getprop ro.build.type')"
if [ "$ROOT" = 1 ] && adb -s "$TV" remount >/dev/null 2>&1; then VENDOR_RW=1; else VENDOR_RW=0; fi

# On a serial-attached device (emulator/USB) the box has no address the Mac can
# reach, so derive its own IP for the cert SAN and verify through a forward.
[ -z "$IP" ] && IP="$(device_ip)"
[ -z "$IP" ] && IP=127.0.0.1
setup_reach || exit 1

echo "   ABI          $BIN"
echo "   adb target   $TV $([ "$NETWORK_ADB" = 1 ] && echo '(network)' || echo '(serial, verifying via adb forward)')"
echo "   build        ${BUILDTYPE:-unknown}"
echo "   adb root     $([ "$ROOT" = 1 ] && echo yes || echo 'no (shell uid)')"
echo "   /vendor rw   $([ "$VENDOR_RW" = 1 ] && echo yes || echo no)"
echo "   SELinux      ${SELINUX:-unknown}"

# Boot persistence needs init, and init only reads service definitions from a
# partition we cannot write on a locked box. Everything else -- serving, key
# injection, the air-mouse -- works as the shell user, because shell is in the
# `input` group. So a non-root box gets a fully working remote that does not
# survive a reboot, rather than no remote at all.
if [ "$VENDOR_RW" = 1 ]; then
  PERSIST=1
  echo "   tier         FULL (boot-persistent)"
else
  PERSIST=0
  echo "   tier         NO-PERSIST (re-run ./deploy.sh after a reboot)"
fi

# Preflight: can this uid actually write the install dir? It can fail even
# though /data/local/tmp is world-writable, because a previous root deploy
# leaves root-owned files that the shell user cannot overwrite. Without this the
# failure surfaces halfway through as a bare "Permission denied" from whichever
# push happened to go first.
# Testing that a NEW file can be created is not enough: /data/local/tmp/tvremote
# is world-writable, so that succeeds while overwriting the root-owned token
# still fails. Test the actual files this deploy will replace.
adb -s "$TV" shell "mkdir -p $REMOTE/bin" >/dev/null 2>&1 || true
unwritable=$(adb -s "$TV" shell "for f in $REMOTE/token $REMOTE/config $REMOTE/boot.sh \
    $REMOTE/bin/tlsproxy $REMOTE/cert.pem $REMOTE/key.pem $REMOTE/ca.crt; do \
      [ -e \$f ] && [ ! -w \$f ] && echo \$f; done; true" 2>/dev/null | tr -d '\r')
if [ -n "$unwritable" ]; then
  echo "!! these files in $REMOTE are not writable as $([ "$ROOT" = 1 ] && echo root || echo 'the shell user'):"
  echo "$unwritable" | sed 's/^/     /'
  if [ "$ROOT" = 0 ]; then
    echo "   It was probably installed by an earlier root deploy. Either re-run"
    echo "   with root, or clear it first:"
    echo "     adb -s $TV root && adb -s $TV shell rm -rf $REMOTE"
  fi
  exit 1
fi

# ---- auth token ------------------------------------------------------------
# Lives only on the device (0600). Reused across deploys on purpose: rotating it
# invalidates every phone's saved home-screen shortcut and cookie.
echo ">> auth token"
tok=$(adb -s "$TV" shell "cat $REMOTE/token 2>/dev/null" | tr -d '\r\n' || true)
if [ "${1:-}" = "--rotate-token" ] || [ -z "$tok" ]; then
  [ -n "$tok" ] && echo "   !! rotating — every phone must reopen the new URL"
  tok=$(openssl rand -hex 16)
  adb -s "$TV" shell "mkdir -p $REMOTE; printf '%s' '$tok' > $REMOTE/token; chmod 600 $REMOTE/token"
  echo "   new token generated"
else
  echo "   reusing existing token"
fi

echo ">> push web app to $REMOTE"
adb -s "$TV" shell "mkdir -p $REMOTE/bin"

# Device-side copy of the config. boot.sh sources this and passes it to the
# proxy as flags, so the on-device binary carries no baked-in address and the
# same binary works on any box.
cat > "$HERE/device/config" <<EOF
# Generated by deploy.sh -- edit config.local.env on the Mac, not this file.
HTTPS_PORT=$HTTPS
REMOTE_DIR=$REMOTE
MDNS_HOST=$MDNS_HOST
ADV_IP=$IP
EOF
adb -s "$TV" push "$HERE/device/config" "$REMOTE/config" >/dev/null
adb -s "$TV" push "$HERE/device/boot.sh"    "$REMOTE/boot.sh"
adb -s "$TV" push "$HERE/device/bin/$BIN" "$REMOTE/bin/tlsproxy"
adb -s "$TV" push "$HERE/device/cert.pem"   "$REMOTE/cert.pem"   # fullchain: leaf + CA
adb -s "$TV" push "$HERE/device/key.pem"    "$REMOTE/key.pem"
adb -s "$TV" push "$HERE/device/ca.crt"     "$REMOTE/ca.crt"     # CA for iPhone to trust
# Sweep the old layout off any box upgraded from it. This is not tidiness:
#
#   start.sh  -- the original launcher, which starts busybox httpd with `-p 8790`
#                and NO 127.0.0.1 prefix, i.e. bound to 0.0.0.0. Anything that
#                ran it would re-expose key.pem and the token to the whole LAN,
#                as root. It is the exact bug this project already fixed once,
#                sitting on disk waiting to be executed.
#   index.html -- the UI is embedded now; a stale copy on disk would be the
#                 wrong UI the moment anything served it again.
#   cgi-bin    -- root-executing scripts with no reason to exist.
adb -s "$TV" shell "rm -rf $REMOTE/cert.crt $REMOTE/index.html $REMOTE/cgi-bin \
    $REMOTE/start.sh $REMOTE/httpd.log; \
  chmod 755 $REMOTE/boot.sh $REMOTE/bin/tlsproxy; \
  chmod 644 $REMOTE/cert.pem $REMOTE/ca.crt; chmod 600 $REMOTE/key.pem $REMOTE/token"

if [ "$PERSIST" = 1 ]; then
  echo ">> install boot service /vendor/etc/init/tvremote.rc"
  adb -s "$TV" push "$HERE/device/tvremote.rc" /vendor/etc/init/tvremote.rc
  adb -s "$TV" shell "chmod 644 /vendor/etc/init/tvremote.rc; chown root:root /vendor/etc/init/tvremote.rc; \
    chcon u:object_r:vendor_configs_file:s0 /vendor/etc/init/tvremote.rc"
else
  echo ">> skipping boot service (/vendor not writable)"
fi

# A box upgraded from the busybox layout has an httpd that init never owned, so
# ctl.restart leaves it running and it keeps serving the install dir on the LAN.
echo ">> stop any stale busybox backend (pre-embed layout)"
# The [t]lsproxy bracket is not a typo: `pkill -f tlsproxy` also matches the
# argv of the very shell running it, so it kills itself before reaching the
# next command. The bracket makes the pattern not match its own literal.
adb -s "$TV" shell "pkill -f '[b]usybox httpd' 2>/dev/null; true" >/dev/null 2>&1 || true

echo ">> (re)start now, no reboot needed"
svc=$(adb -s "$TV" shell 'getprop init.svc.tvremote' | tr -d '\r')
if [ "$PERSIST" = 1 ] && [ -n "$svc" ]; then
  # init owns the service (installed on a prior boot) -> just re-exec it
  adb -s "$TV" shell "setprop ctl.restart tvremote" >/dev/null 2>&1 || true
else
  # No init service, or it exists but has never been started. Launch detached so
  # adb returns; kill any predecessor first, because a survivor still holding
  # :$HTTPS makes the new binary die on bind while the OLD one keeps serving --
  # the verify below would then pass against code you thought you replaced.
  adb -s "$TV" shell "pkill -f '[t]lsproxy' 2>/dev/null; sleep 1; \
    ( setsid /system/bin/sh $REMOTE/boot.sh >$REMOTE/boot.log 2>&1 </dev/null & ); exit" >/dev/null 2>&1 || true
fi

echo ">> verify"
sleep 3
# curl prints 000 to stdout on a connection failure but also exits nonzero, which
# set -e would treat as fatal; swallow the status and keep the code.
code(){ local c; c=$(curl -sk -m6 -o /dev/null -w '%{http_code}' "$@" 2>/dev/null) || c=000; echo "${c:-000}"; }

noauth=$(code "https://$REACH_HOST:$REACH_PORT/")                 # must be 401
auth=$(code -H "Cookie: tvr=$tok" "https://$REACH_HOST:$REACH_PORT/")
ca=$(code "http://$REACH_HOST:$REACH_PORT/ca.crt")                # plaintext bootstrap, must be 200
# Proves input injection really runs, not just that the server answers. Paired
# up/down so the check leaves the volume where it found it.
key=$(code -H "Cookie: tvr=$tok" "https://$REACH_HOST:$REACH_PORT/cgi-bin/k?volup")
code -H "Cookie: tvr=$tok" "https://$REACH_HOST:$REACH_PORT/cgi-bin/k?voldown" >/dev/null
# Nothing is served off the filesystem now, but assert it anyway: this pair is
# what caught the TLS private key being downloadable over the LAN, and a future
# static-file handler would silently reintroduce it.
leakkey=$(code -H "Cookie: tvr=$tok" "https://$REACH_HOST:$REACH_PORT/key.pem")
leaktok=$(code -H "Cookie: tvr=$tok" "https://$REACH_HOST:$REACH_PORT/token")
# The UI must actually come back. A 200 alone would also be satisfied by an
# empty body if the embed ever broke.
ui=$(curl -sk -m6 -H "Cookie: tvr=$tok" "https://$REACH_HOST:$REACH_PORT/" 2>/dev/null | grep -c '<html' || true)
# Upgrade hazard, not a permanent one: a box deployed under the old layout has a
# busybox httpd that init does not supervise, so it survives ctl.restart and
# keeps serving the whole install dir as root on the LAN. Assert it is gone.
# `grep -c` exits 1 on zero matches, so the || has to live INSIDE the device
# shell -- putting it outside appends a second value to the one grep printed.
stray=$(adb -s "$TV" shell "toybox netstat -ltn 2>/dev/null | grep -c ':$LEGACY_BACKEND_PORT ' || true" | tr -d '\r' | head -1)

echo "   no token           https://$REACH_HOST:$REACH_PORT/          -> $noauth   (want 401)"
echo "   with token         https://$REACH_HOST:$REACH_PORT/          -> $auth   (want 200)"
echo "   UI body served     <html> in response           -> $ui   (want 1)"
echo "   CA over plaintext  http://$REACH_HOST:$REACH_PORT/ca.crt     -> $ca   (want 200)"
echo "   a key press        …/cgi-bin/k?volup            -> $key   (want 200)"
echo "   TLS key w/ token   …/key.pem                    -> $leakkey   (want 404)"
echo "   token w/ token     …/token                      -> $leaktok   (want 404)"
echo "   stale busybox      listeners on :$LEGACY_BACKEND_PORT           -> $stray   (want 0)"

fail=0
[ "$noauth" = 401 ] || { echo "!! unauthenticated request was not rejected"; fail=1; }
[ "$auth"   = 200 ] || { echo "!! tokenized request failed"; fail=1; }
[ "$ui"     = 1   ] || { echo "!! the page came back empty — the embedded UI is broken"; fail=1; }
[ "$ca"     = 200 ] || { echo "!! ca.crt not served in the clear — a new phone can't bootstrap trust"; fail=1; }
[ "$key"     = 200 ] || { echo "!! key injection endpoint failed"; fail=1; }
[ "$leakkey" = 404 ] || { echo "!! the TLS PRIVATE KEY is downloadable"; fail=1; }
[ "$leaktok" = 404 ] || { echo "!! the auth token itself is downloadable"; fail=1; }
[ "$stray"   = 0   ] || { echo "!! a stale busybox httpd is still serving the install dir on :$LEGACY_BACKEND_PORT"; fail=1; }
if [ "$fail" != 0 ]; then
  # The server's own startup error is the single most useful thing here and it
  # is already on the device. Without this every startup failure -- port taken,
  # bad cert, missing token -- looks identical from the Mac: a wall of 000.
  echo
  echo "--- $REMOTE/boot.log (on the device) ---"
  adb -s "$TV" shell "tail -20 $REMOTE/boot.log 2>/dev/null" | sed 's/^/   /' || true
  case "$(adb -s "$TV" shell "tail -5 $REMOTE/boot.log 2>/dev/null" | tr -d '\r')" in
    *"address already in use"*)
      echo
      echo "   Port $HTTPS is taken by something else on this box. Set a different"
      echo "   HTTPS_PORT in config.local.env and re-run. (Some Android TV builds"
      echo "   ship services on 8443/6466/6467/8008.)" ;;
  esac
  echo
  echo "FAILED (see also: ./logs.sh)"
  exit 1
fi

echo "OK."

# What this box can actually do. Reported after the deploy succeeds because it
# is answered by the running server, not guessed from properties -- evdev access
# depends on SELinux policy, which uid and group membership do not reveal.
caps=$(curl -sk -m6 -H "Cookie: tvr=$tok" "https://$REACH_HOST:$REACH_PORT/caps" 2>/dev/null || true)
case "$caps" in
  *'"pointer":true'*) ptr="yes" ;;
  *'"pointer":false'*) ptr="NO" ;;
  *) ptr="?" ;;
esac
case "$caps" in
  *'"heldKey":true'*) hold="yes" ;;
  *'"heldKey":false'*) hold="NO" ;;
  *) hold="?" ;;
esac
echo
echo "Features on this box:"
echo "   keys / text / apps    yes"
echo "   touchpad (air-mouse)  $ptr"
echo "   hold-OK context menu  $hold"
if [ "$ptr" = "NO" ] || [ "$hold" = "NO" ]; then
  echo
  echo "   evdev is not writable here. That is expected on an SELinux-Enforcing"
  echo "   box without root: policy denies /dev/input and /dev/uinput to the shell"
  echo "   domain regardless of the 'input' group. The remote still works — the"
  echo "   touchpad and the held-OK gesture are the only things unavailable."
fi
if [ "$PERSIST" != 1 ]; then
  echo
  echo "NOTE: no boot persistence on this box — /vendor is not writable, and init"
  echo "      only reads service definitions from a partition we cannot write."
  echo "      Everything works until the box reboots; then re-run ./deploy.sh"
  echo "      (or just: adb -s $TV shell \"( setsid /system/bin/sh $REMOTE/boot.sh & )\")"
fi
echo
echo "REMOTE URL (contains the token — treat it like a password):"
echo "  https://$IP:$HTTPS/?t=$tok"
echo
echo "iPhone (one-time): DELETE any old 'Projector Remote' profile first, then:"
echo "  1) Safari -> http://$IP:$HTTPS/ca.crt  -> install the 'Projector Remote Local CA' profile"
echo "  2) Settings > General > About > Certificate Trust Settings -> turn it ON"
echo "  3) force-quit Safari, then open the tokenized URL above -> Add to Home Screen"
echo "     (add it WITH ?t=… so the shortcut re-authorizes itself if the cookie is ever evicted)"
